DROP DATABASE hotel_management_panel_inserts;

-- MySQL Script generated by MySQL Workbench
-- Tue Apr 24 21:06:46 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hotel_management_panel_inserts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hotel_management_panel_inserts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel_management_panel_inserts` DEFAULT CHARACTER SET utf8 ;
USE `hotel_management_panel_inserts` ;

-- -----------------------------------------------------
-- Table `hotel_management_panel_inserts`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management_panel_inserts`.`Location` (
  `resortShortName` VARCHAR(2) NOT NULL,
  `resortName` VARCHAR(50) NOT NULL,
  `city` VARCHAR(20) NOT NULL,
  `postcode` VARCHAR(6) NOT NULL,
  `street` VARCHAR(30) NOT NULL,
  `parcel` INT NOT NULL,
  PRIMARY KEY (`resortShortName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_management_panel_inserts`.`Room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management_panel_inserts`.`Room` (
  `idRoom` VARCHAR(7) GENERATED ALWAYS AS (CONCAT(roomNumber,floorNumber,Location_resortShortName)) STORED,
  `floorNumber` CHAR(2) NOT NULL,
  `roomNumber` CHAR(3) NOT NULL,
  `size` INT(1) NOT NULL DEFAULT 2,
  `price` INT UNSIGNED NOT NULL DEFAULT 300,
  `Location_resortShortName` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idRoom`),
  CONSTRAINT `fk_Room_Location1`
    FOREIGN KEY (`Location_resortShortName`)
    REFERENCES `hotel_management_panel_inserts`.`Location` (`resortShortName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

#CREATE UNIQUE INDEX `idRoom_UNIQUE` ON `hotel_management_panel_inserts`.`Room` (`idRoom` ASC);

#CREATE INDEX `fk_Room_Location1_idx` ON `hotel_management_panel_inserts`.`Room` (`Location_resortShortName` ASC);


-- -----------------------------------------------------
-- Table `hotel_management_panel_inserts`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management_panel_inserts`.`Employee` (
  `PESEL` VARCHAR(11) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `surname` VARCHAR(15) NOT NULL,
  `telNumber` VARCHAR(9) NULL,
  `salary` INT NOT NULL DEFAULT 2000,
  PRIMARY KEY (`PESEL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_management_panel_inserts`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management_panel_inserts`.`Client` (
  `login` VARCHAR(15) NOT NULL,
  `password` VARCHAR(15) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  `surname` VARCHAR(15) NOT NULL,
  `telNumber` VARCHAR(9) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`login`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel_management_panel_inserts`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management_panel_inserts`.`Reservation` (
  `idReservation` INT UNSIGNED NOT NULL,
  `status` ENUM ('inProgress', 'canceledClient', 'canceledSystem', 'before', 'after', 'during') NOT NULL,
  `cost` INT UNSIGNED NOT NULL,
  `firstDay` DATE NOT NULL,
  `lastDay` DATE NOT NULL,
  `breakfast` TINYINT NOT NULL,
  `Client_login` VARCHAR(15) NOT NULL,
  `Room_idRoom` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`idReservation`),
  CONSTRAINT `fk_Reservation_Client`
    FOREIGN KEY (`Client_login`)
    REFERENCES `hotel_management_panel_inserts`.`Client` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservation_Room1`
    FOREIGN KEY (`Room_idRoom`)
    REFERENCES `hotel_management_panel_inserts`.`Room` (`idRoom`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

#CREATE UNIQUE INDEX `idReservation_UNIQUE` ON `hotel_management_panel_inserts`.`Reservation` (`idReservation` ASC);

#CREATE INDEX `fk_Reservation_Client_idx` ON `hotel_management_panel_inserts`.`Reservation` (`Client_login` ASC);

#CREATE INDEX `fk_Reservation_Room1_idx` ON `hotel_management_panel_inserts`.`Reservation` (`Room_idRoom` ASC);


-- -----------------------------------------------------
-- Table `hotel_management_panel_inserts`.`Employee_has_Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hotel_management_panel_inserts`.`Employee_has_Location` (
  `Employee_PESEL` VARCHAR(11) NOT NULL,
  `Location_resortShortName` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`Employee_PESEL`, `Location_resortShortName`),
  CONSTRAINT `fk_Employee_has_Location_Employee1`
    FOREIGN KEY (`Employee_PESEL`)
    REFERENCES `hotel_management_panel_inserts`.`Employee` (`PESEL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employee_has_Location_Location1`
    FOREIGN KEY (`Location_resortShortName`)
    REFERENCES `hotel_management_panel_inserts`.`Location` (`resortShortName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

#CREATE INDEX `fk_Employee_has_Location_Employee1_idx` ON `hotel_management_panel_inserts`.`Employee_has_Location` (`Employee_PESEL` ASC);

#CREATE INDEX `fk_Employee_has_Location_Location1_idx` ON `hotel_management_panel_inserts`.`Employee_has_Location` (`Location_resortShortName` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE hotel_management_panel_inserts;

SHOW tables;